# Generated by Django 4.0.3 on 2022-05-26 02:41

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
