# Generated by Django 4.0.3 on 2022-05-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
