# Generated by Django 4.0.3 on 2022-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_username', models.CharField(max_length=50)),
                ('User_password', models.CharField(max_length=100)),
                ('User_name', models.CharField(max_length=50)),
            ],
        ),
    ]
