# Generated by Django 4.0.3 on 2022-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_img',
            field=models.TextField(null=True),
        ),
    ]
