# Generated by Django 4.0.3 on 2022-06-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_users_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='User_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='User_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
