# Generated by Django 4.0.3 on 2022-05-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0002_blog_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment_content', models.TextField()),
                ('Comment_date', models.DateTimeField()),
                ('Comment_blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
            ],
        ),
    ]
