# Generated by Django 4.0.3 on 2022-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
