# Generated by Django 4.0.3 on 2022-06-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_users_user_address_users_user_email_users_user_phone'),
        ('Comment', '0003_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
    ]
