# Generated by Django 4.0.3 on 2022-05-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('ReplyComment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ReplyComment_content', models.TextField()),
                ('ReplyComment_date', models.DateTimeField()),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.comment')),
            ],
        ),
    ]
